name: Acme Lab actions

on:
  workflow_dispatch:
    inputs:
      AA:
        type: string
        default: default
        description: AA
  push:
    branches:
      - main
      - master
      - develop

jobs:
  job-1:
    name: Job 1 name
    runs-on: ubuntu-latest
    steps:
      - name: Step 1.1 name
        id: step-1-1
        shell: bash
        run: echo "Hello world"
      - name: Step 1.2 name
        id: step-1-2
        shell: sh
        run: echo "id=Ya ma7leha ya baba ya 7anni" >> $GITHUB_OUTPUT
      - name: Step 1.3 name
        id: step-1-3
        shell: bash
        env:
          COOL_VAR: ${{ steps.step-1-2.outputs.id }}
        run: |
          echo "COOL_VAR => '${{ env.COOL_VAR }}'"
    outputs:
      another_name: ${{ steps.step-1-2.outputs.id }}

  job-2:
    name: Job 2
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - name: Step 2.1 name
        id: step-2-1
        shell: bash
        run: |
          echo "Hello world, this is output from first-job : '${{ needs.job-1.outputs.another_name }}'"

  job-3:
    name: Job 3
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs:
      - job-1
      - job-2
    steps:
      - name: Step 3.1 name
        id: step-3-1
        shell: bash
        run: |
          echo "JOB 3 : SUCCESS"

  job-4:
    name: Job 4
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs:
      - job-1
      - job-2
    steps:
      - name: Step 4.1 name
        id: step-4-1
        shell: bash
        run: |
          echo "JOB 4 : FAIULRE"

  job-5:
    name: Job 5
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - job-1
      - job-2
    steps:
      - name: Step 5.1
        id: step-5-1
        shell: bash
        run: |
          echo "List all functions";
          declare -F
      - name: Step 5.2
        id: step-5-2
        shell: bash
        run: |
          echo "List all functions and their definition";
          declare -f
      - name: Step 5.3
        id: step-5-3
        shell: bash
        run: |
          echo "List all variables";
          env
