name: multistage

on:
  push:
    branches:
      - main
      - master
      - develop

permissions:
  contents: write
  packages: write

env:
  BASE_IMAGE_NAME: ghcr.io/kidager/test-php-image
  CRON_IMAGE_NAME: ghcr.io/kidager/test-cron-image
  WORKER_IMAGE_NAME: ghcr.io/kidager/test-worker-image
  CACHE_TAG: cache

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare base image metadata
        id: base-image-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.BASE_IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.sha }}
            type=raw,value=latest

      - name: Build base image
        uses: docker/build-push-action@v6
        env:
          CACHE_TO: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=${{ env.WORKER_IMAGE_NAME }}:${{ env.CACHE_TAG }}
          CACHE_FROM: type=registry,ref=${{ env.WORKER_IMAGE_NAME }}:${{ env.CACHE_TAG }}
        with:
          push: true
          file: docker/base.Dockerfile
          tags: ${{ steps.base-image-metadata.outputs.tags }}
          cache-from: ${{ env.CACHE_FROM }}
          cache-to: ${{ github.event_name == 'release' && env.CACHE_TO || null }}

      - name: Prepare worker image metadata
        id: worker-image-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.WORKER_IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.sha }}
            type=raw,value=latest

      - name: Build worker image
        uses: docker/build-push-action@v6
        env:
          CACHE_TO: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=${{ env.CRON_IMAGE_NAME }}:${{ env.CACHE_TAG }}
          CACHE_FROM: type=registry,ref=${{ env.CRON_IMAGE_NAME }}:${{ env.CACHE_TAG }}
        with:
          push: true
          file: docker/worker.Dockerfile
          build-contexts: |
            base-php-image=docker-image://${{ steps.base-image-metadata.outputs.tags }}
          tags: ${{ steps.worker-image-metadata.outputs.tags }}
          cache-from: ${{ env.CACHE_FROM }}
          cache-to: ${{ github.event_name == 'release' && env.CACHE_TO || null }}

      - name: Prepare cron image metadata
        id: cron-image-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.CRON_IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.sha }}
            type=raw,value=latest

      - name: Build cron image
        uses: docker/build-push-action@v6
        env:
          CACHE_TO: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=${{ env.BASE_IMAGE_NAME }}:${{ env.CACHE_TAG }}
          CACHE_FROM: type=registry,ref=${{ env.BASE_IMAGE_NAME }}:${{ env.CACHE_TAG }}
        with:
          push: true
          file: docker/cron.Dockerfile
          build-contexts: |
            base-php-image=docker-image://${{ steps.base-image-metadata.outputs.tags }}
          tags: ${{ steps.cron-image-metadata.outputs.tags }}
          cache-from: ${{ env.CACHE_FROM }}
          cache-to: ${{ github.event_name == 'release' && env.CACHE_TO || null }}
